version: '3'

networks: 
  network-producao:
    driver: bridge

services: 
  
  nginx: 
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: renandmc/nginx
    container_name: nginx
    ports: 
      - '8080:80'
    networks: 
      - network-producao
    depends_on: 
      - 'node1'
      - 'node2'
      - 'node3'
  
  mongodb:
    image: mongo
    networks: 
      - network-producao
  
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: renandmc/alura-books
    container_name: alura-books-1
    ports: 
      - '3000'
    networks: 
      - network-producao
    depends_on: 
      - 'mongodb'
  
  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: renandmc/alura-books
    container_name: alura-books-2
    ports: 
      - '3000'
    networks: 
      - network-producao
    depends_on: 
      - 'mongodb'
  
  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: renandmc/alura-books
    container_name: alura-books-3
    ports: 
      - '3000'
    networks: 
      - network-producao
    depends_on: 
      - 'mongodb'